# Generated by Django 5.2 on 2025-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('General', 'General')], max_length=10, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course', models.CharField(blank=True, choices=[('BBA', 'BBA'), ('BCom', 'BCom'), ('BCA', 'BCA'), ('BA.LL.B(Hon)', 'BA.LL.B(Hon)'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('LL.B(Hon)', 'LL.B(Hon)')], max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income', models.CharField(blank=True, max_length=50, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('x_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('x_year', models.CharField(blank=True, max_length=10, null=True)),
                ('x_board', models.CharField(blank=True, max_length=50, null=True)),
                ('xii_stream_percent', models.CharField(blank=True, max_length=100, null=True)),
                ('xii_year', models.CharField(blank=True, max_length=10, null=True)),
                ('xii_board', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('grad_stream_percent', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('src_website', models.BooleanField(default=False)),
                ('src_newspaper', models.BooleanField(default=False)),
                ('src_hoarding', models.BooleanField(default=False)),
                ('src_calling', models.BooleanField(default=False)),
                ('src_ads', models.BooleanField(default=False)),
                ('src_other', models.BooleanField(default=False)),
                ('src_other_text', models.CharField(blank=True, max_length=200, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
