# Generated by Django 5.2 on 2025-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinquiry',
            name='course',
            field=models.CharField(blank=True, choices=[('BBA', 'BBA'), ('BCom', 'BCom'), ('BCA', 'BCA'), ('BA.LL.B(Hon)', 'BA.LL.B(Hon)'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('LL.B(Hon)', 'LL.B(Hon)')], max_length=30, null=True),
        ),
    ]
